// Code generated by "enumer -type=Kind"; DO NOT EDIT.

package behaviortree

import (
	"fmt"
	"strings"
)

const _KindName = "SequenceSelectorRepeatorInverterTask"

var _KindIndex = [...]uint8{0, 8, 16, 24, 32, 36}

const _KindLowerName = "sequenceselectorrepeatorinvertertask"

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_KindIndex)-1) {
		return fmt.Sprintf("Kind(%d)", i)
	}
	return _KindName[_KindIndex[i]:_KindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _KindNoOp() {
	var x [1]struct{}
	_ = x[Sequence-(0)]
	_ = x[Selector-(1)]
	_ = x[Repeator-(2)]
	_ = x[Inverter-(3)]
	_ = x[Task-(4)]
}

var _KindValues = []Kind{Sequence, Selector, Repeator, Inverter, Task}

var _KindNameToValueMap = map[string]Kind{
	_KindName[0:8]:        Sequence,
	_KindLowerName[0:8]:   Sequence,
	_KindName[8:16]:       Selector,
	_KindLowerName[8:16]:  Selector,
	_KindName[16:24]:      Repeator,
	_KindLowerName[16:24]: Repeator,
	_KindName[24:32]:      Inverter,
	_KindLowerName[24:32]: Inverter,
	_KindName[32:36]:      Task,
	_KindLowerName[32:36]: Task,
}

var _KindNames = []string{
	_KindName[0:8],
	_KindName[8:16],
	_KindName[16:24],
	_KindName[24:32],
	_KindName[32:36],
}

// KindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func KindString(s string) (Kind, error) {
	if val, ok := _KindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _KindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Kind values", s)
}

// KindValues returns all values of the enum
func KindValues() []Kind {
	return _KindValues
}

// KindStrings returns a slice of all String values of the enum
func KindStrings() []string {
	strs := make([]string, len(_KindNames))
	copy(strs, _KindNames)
	return strs
}

// IsAKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Kind) IsAKind() bool {
	for _, v := range _KindValues {
		if i == v {
			return true
		}
	}
	return false
}
