// Code generated by "enumer -type=Status"; DO NOT EDIT.

package behaviortree

import (
	"fmt"
	"strings"
)

const _StatusName = "DormantRunningFailureSuccess"

var _StatusIndex = [...]uint8{0, 7, 14, 21, 28}

const _StatusLowerName = "dormantrunningfailuresuccess"

func (i Status) String() string {
	i -= -1
	if i < 0 || i >= Status(len(_StatusIndex)-1) {
		return fmt.Sprintf("Status(%d)", i+-1)
	}
	return _StatusName[_StatusIndex[i]:_StatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _StatusNoOp() {
	var x [1]struct{}
	_ = x[Dormant-(-1)]
	_ = x[Running-(0)]
	_ = x[Failure-(1)]
	_ = x[Success-(2)]
}

var _StatusValues = []Status{Dormant, Running, Failure, Success}

var _StatusNameToValueMap = map[string]Status{
	_StatusName[0:7]:        Dormant,
	_StatusLowerName[0:7]:   Dormant,
	_StatusName[7:14]:       Running,
	_StatusLowerName[7:14]:  Running,
	_StatusName[14:21]:      Failure,
	_StatusLowerName[14:21]: Failure,
	_StatusName[21:28]:      Success,
	_StatusLowerName[21:28]: Success,
}

var _StatusNames = []string{
	_StatusName[0:7],
	_StatusName[7:14],
	_StatusName[14:21],
	_StatusName[21:28],
}

// StatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func StatusString(s string) (Status, error) {
	if val, ok := _StatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _StatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Status values", s)
}

// StatusValues returns all values of the enum
func StatusValues() []Status {
	return _StatusValues
}

// StatusStrings returns a slice of all String values of the enum
func StatusStrings() []string {
	strs := make([]string, len(_StatusNames))
	copy(strs, _StatusNames)
	return strs
}

// IsAStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Status) IsAStatus() bool {
	for _, v := range _StatusValues {
		if i == v {
			return true
		}
	}
	return false
}
